import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#281800",
        "on-primary-fixed-variant": "#6e3900",
        "primary-fixed": "#ffdcc3",
        "tertiary-fixed": "#c7e7ff",
        "on-tertiary-fixed-variant": "#004c6c",
        "on-tertiary-fixed": "#001e2e",
        "surface-container-low": "#fff1e3",
        "on-secondary": "#ffffff",
        "on-background": "#211b12",
        "tertiary-container": "#00b5fc",
        "on-error-container": "#93000a",
        "surface-variant": "#eee0d2",
        "inverse-surface": "#362f26",
        "surface-tint": "#904d00",
        "on-primary-container": "#623200",
        "inverse-on-surface": "#fcefe0",
        "surface-dim": "#e5d8ca",
        error: "#ba1a1a",
        background: "#fff8f3",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#2f1500",
        surface: "#fff8f3",
        "on-primary": "#ffffff",
        "primary-container": "#ff8c00",
        "surface-bright": "#fff8f3",
        "primary-fixed-dim": "#ffb77d",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#ffb77d",
        "surface-container-highest": "#eee0d2",
        "surface-container": "#f9ecde",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#ddc1ae",
        "surface-container-high": "#f3e6d8",
        tertiary: "#00658f",
        "on-secondary-container": "#795513",
        "secondary-fixed-dim": "#f0be74",
        outline: "#897362",
        "secondary-fixed": "#ffddb0",
        "tertiary-fixed-dim": "#85cfff",
        secondary: "#7c5716",
        "on-secondary-fixed-variant": "#614000",
        "secondary-container": "#ffcc80",
        "on-surface": "#211b12",
        "on-surface-variant": "#564334",
        "on-error": "#ffffff",
        "on-tertiary-container": "#004360",
        primary: "#904d00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "stack-sm": "12px",
        "stack-lg": "48px",
        "container-max": "1200px",
        base: "8px",
        "stack-md": "24px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Libre Caslon Text"],
        "label-sm": ["DM Sans"],
        "label-md": ["DM Sans"],
        "body-lg": ["DM Sans"],
        "body-md": ["DM Sans"],
        "headline-lg": ["Libre Caslon Text"],
        "headline-md": ["Libre Caslon Text"],
        "headline-xl": ["Libre Caslon Text"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "1.3", fontWeight: "600" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "700" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-xl": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
      },
    },
  },
} satisfies Config;
